speechkit v3
lEx0/yatts pull request #2
Opened 2023-01-25 09:20 UTC by lEx0

реализация клиента под GRPC v3 версию SpeechKit -а

2023-01-25 10:31 UTC, danikk741 approved these changes

2023-01-25 10:58 UTC, antonsergeyev requested changes

2023-01-25 10:58 UTC, antonsergeyev commented on v3/auth/auth.go
> +	getIamTokenFunc func() (string, error)
а почему тип неэкспортируемый? это не создаст проблем?

2023-01-25 10:58 UTC, antonsergeyev commented on v3/auth/auth_test.go
> +			t.Error("metadata must be exists")
не критично, но везде, где написано "must be eixsts" должно быть "must exist"

2023-01-25 10:58 UTC, antonsergeyev commented on v3/auth/auth_test.go
> +			t.Error("authorization value must be Bearer token")
может быть must be "Api-Key token"?

2023-01-25 10:58 UTC, antonsergeyev commented on v3/yatts.go
> +		credentials.NewTLS(&tls.Config{}),
тут не нужна возможность получить transport credentials в аргументе?

2023-01-25 10:58 UTC, antonsergeyev commented on v3/yatts.go
> +				_ = pw.CloseWithError(err)
а точно нужен возврат при ошибках чтения\записи?
предположим, был временный затуп с сетью - и мы остановим работу, это ок?

2023-01-26 05:42 UTC, lEx0 commented on v3/auth/auth.go
> +	getIamTokenFunc func() (string, error)
да создаст, подправлю

2023-01-26 05:43 UTC, lEx0 commented on v3/auth/auth_test.go
> +			t.Error("metadata must be exists")
ок подправлю, текст от copilot

2023-01-26 05:43 UTC, lEx0 commented on v3/auth/auth_test.go
> +			t.Error("authorization value must be Bearer token")
ты прав

2023-01-26 05:44 UTC, lEx0 commented on v3/yatts.go
> +		credentials.NewTLS(&tls.Config{}),
а там не надо никаких кредов, просто сигнализируем что grpc работает через 443 порт, и там подсосутся дефолтные значения.
уже работает в распознании речи так

2023-01-26 05:46 UTC, lEx0 commented on v3/yatts.go
> +				_ = pw.CloseWithError(err)
тут несколько проблем.
например: в некоторых голосах нет эмоций (nigora)
и если передашь, ты получишь ошибку со стороны grpc, и надо как то просигнализировать об этом
второе, grpc может же переподключаться, и сам должен сгладить это. если не смог, уже ошибка и это норм

2023-01-26 07:43 UTC, antonsergeyev approved these changes

2023-01-26 08:43 UTC, merged